# backend related values
backend:
  depl_name: "backend-depl"
  service_name: "backend-svc"
  # db_hostname: "mysql-sts-0.mysql-headless"
  file_storage_dir: "/app/file_storage/"

  replicas: 1
  image:
    repository: "greninja517/backend"
    tag: "1.0"


# frontend related configurations
frontend:
  depl_name: "frontend-depl"
  service_name: "frontend-svc"
  replicas: 1
  image:
    repository: "greninja517/frontend"
    tag: "1.0"


# database related configurations
database:
  statefulset_name: "mysql-sts"
  headless_svc_name: "mysql-headless"
  replicas: 1

  image:
    repository: "mysql"
    tag: "latest"

  # these values shouldn't be exposed to public. This is for demo purpose only.
  root_user: "root"
  root_password: "Root@123"

  
# ingress related
ingress:
  # provide your domain name for the application
  domain_name : "file.cloud-ninja.xyz"


 

