apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.domain_name }} # Replace with your DNS name
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-svc
            port:
              number: 80 # Frontend service's ClusterIP port
      - path: /upload-file
        pathType: Exact
        backend:
          service:
            name: backend-svc
            port:
              number: 9090 # Backend service's ClusterIP port
      - path: /download
        pathType: Prefix # Allows for query parameters like ?pin=...
        backend:
          service:
            name: backend-svc
            port:
              number: 9090 # Backend service's ClusterIP port