apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-depl
  namespace: 3-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend
        image: greninja517/backend:1.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: db_username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: db_password
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: backend-cfg
                key: database_url
          - name: FILE_STORAGE_DIRECTORY
            valueFrom:
              configMapKeyRef:
                name: backend-cfg
                key: file_storage_dir 
        volumeMounts:
        - name: backend-vol
          mountPath: "/app/file_storage/"
      volumes: 
        - name: backend-vol
          persistentVolumeClaim:
            claimName: backend-pvc
        

            
 