apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: 3-tier-app
  name: backend-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: backend-storage
  accessModes:
    - ReadWriteOnce
