apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service_name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: frontend-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
