apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service_name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: backend-app
  ports:
  - port: 9090
    targetPort: 9090
