apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: backend-cfg
data:
  database_url: "jdbc:mysql://{{ .Values.database.statefulset_name }}-0.{{ .Values.database.headless_svc_name }}:3306/fileSharer?createDatabaseIfNotExist=true"