apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.database.statefulset_name }} #mysql-sts
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: mydb
  serviceName: {{ .Values.database.headless_svc_name }} #mysql-headless
  replicas: {{ .Values.database.replicas }}
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
      - name: mysql
        image: {{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ required "database password is required. Use --set database.root_password=<password>" .Values.database.root_password }}
          # valueFrom:
          #   secretKeyRef:
          #     key: root_password
          #     name: db-secret
        volumeMounts:
        - name: mysql-vol
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-vol
    spec:
      resources:
        requests:
          storage: 5Gi
      volumeMode: Filesystem
      storageClassName: mysql-storage
      accessModes:
        - ReadWriteOnce
