# this headless service is only for giving unique dns name to each db pod. If more than one db pod is used, then another clusterIP should be created and that svc should be used for read only purpose by other applications. For writing to a database, only a single pod is used. So, it requires headless svc to forward traffic directly to that node.
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.headless_svc_name }} #mysql-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app: mydb
  ports:
  - port: 3306
    targetPort: 3306
